-- Дополнение к схеме profiles из второй лабораторной.
begin;
create table if not exists public.cars (
 id bigint generated by default as identity primary key,
 client_id uuid not null unique,
 owner_id uuid references auth.users(id) on delete cascade,
 brand text not null check(length(trim(brand))>0),
 model text not null check(length(trim(model))>0),
 year integer not null check(year between 1900 and 2100),
 transmission text not null,
 mileage integer not null default 0 check(mileage>=0),
 description text not null default '',
 address text not null,
 price_per_day integer not null default 3000 check(price_per_day>0),
 insurance_per_day integer not null default 500 check(insurance_per_day>=0),
 deposit integer not null default 10000 check(deposit>=0),
 photo_paths jsonb not null default '[]'::jsonb check(jsonb_typeof(photo_paths)='array' and jsonb_array_length(photo_paths)<=5),
 active boolean not null default false
);
alter table public.cars enable row level security;
revoke all on public.cars from anon, authenticated;
grant select,insert,update on public.cars to authenticated;
grant usage,select on sequence public.cars_id_seq to authenticated;
drop policy if exists cars_read on public.cars;
create policy cars_read on public.cars for select to authenticated using(active or owner_id=auth.uid());
drop policy if exists cars_insert on public.cars;
create policy cars_insert on public.cars for insert to authenticated with check(owner_id=auth.uid() and not active);
drop policy if exists cars_update on public.cars;
create policy cars_update on public.cars for update to authenticated using(owner_id=auth.uid()) with check(
 owner_id=auth.uid() and (not active or jsonb_array_length(photo_paths) between 1 and 5)
 and not exists(select 1 from jsonb_array_elements_text(photo_paths) as f(path) where left(f.path,37)<>auth.uid()::text||'/'));

create table if not exists public.bookings (
 id uuid primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 car_id bigint not null references public.cars(id),
 car_name text not null,
 address text not null,
 driver_name text not null,
 license_number text not null,
 start_date date not null,
 end_date date not null check(end_date>=start_date),
 price_per_day integer not null,
 rental_total bigint not null,
 insurance_total bigint not null,
 deposit integer not null,
 total bigint not null,
 status text not null default 'approved' check(status in ('approved','cancelled')),
 created_at timestamptz not null default now()
);
alter table public.bookings enable row level security;
revoke all on public.bookings from anon,authenticated;
grant select on public.bookings to authenticated;
drop policy if exists bookings_read on public.bookings;
create policy bookings_read on public.bookings for select to authenticated using(user_id=auth.uid());

create or replace function public.create_booking(p_request uuid,p_car bigint,p_start date,p_end date)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.cars; b public.bookings; p public.profiles; days bigint;
begin
 if auth.uid() is null then raise exception 'Войдите в аккаунт'; end if;
 if p_request is null or p_start is null or p_end is null or p_start<current_date or p_end<p_start or p_end>p_start+365 then
   raise exception 'Проверьте даты: начало не раньше сегодня, срок от 1 до 366 дней'; end if;
 perform pg_advisory_xact_lock(p_car);
 select * into b from public.bookings where id=p_request;
 if found then
   if b.user_id<>auth.uid() or b.car_id<>p_car or b.start_date<>p_start or b.end_date<>p_end then raise exception 'Повторный запрос не совпадает с бронированием'; end if;
   return to_jsonb(b);
 end if;
 select * into c from public.cars where id=p_car and active;
 if not found then raise exception 'Автомобиль недоступен'; end if;
 select * into p from public.profiles where id=auth.uid();
 if not found or length(trim(p.name))=0 or length(trim(p.surname))=0 or p.license_number is null or length(p.license_number)<>10 then
   raise exception 'Заполните имя, фамилию и номер удостоверения в профиле'; end if;
 if exists(select 1 from public.bookings where car_id=p_car and status='approved' and daterange(start_date,end_date+1,'[)') && daterange(p_start,p_end+1,'[)')) then
   raise exception 'Автомобиль уже забронирован на выбранные даты'; end if;
 days:=p_end-p_start+1;
 insert into public.bookings(id,user_id,car_id,car_name,address,driver_name,license_number,start_date,end_date,price_per_day,rental_total,insurance_total,deposit,total)
 values(p_request,auth.uid(),c.id,c.brand||' '||c.model,c.address,concat_ws(' ',p.surname,p.name,nullif(p.patronymic,'')),p.license_number,p_start,p_end,c.price_per_day,days*c.price_per_day,days*c.insurance_per_day,c.deposit,days*c.price_per_day+days*c.insurance_per_day)
 returning * into b;
 return to_jsonb(b);
end $$;
revoke all on function public.create_booking(uuid,bigint,date,date) from public,anon;
grant execute on function public.create_booking(uuid,bigint,date,date) to authenticated;
create or replace function public.cancel_booking(p_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if auth.uid() is null then raise exception 'Войдите в аккаунт'; end if;
 if exists(select 1 from public.bookings where id=p_id and user_id=auth.uid() and status='cancelled') then return; end if;
 update public.bookings set status='cancelled' where id=p_id and user_id=auth.uid() and status='approved' and end_date>=current_date;
 if not found then raise exception 'Активное бронирование не найдено'; end if;
end $$;
revoke all on function public.cancel_booking(uuid) from public,anon;
grant execute on function public.cancel_booking(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('car-photos','car-photos',false,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
drop policy if exists car_photos_read on storage.objects;
create policy car_photos_read on storage.objects for select to authenticated using(bucket_id='car-photos' and
 ((storage.foldername(name))[1]=auth.uid()::text or exists(select 1 from public.cars c where c.active and c.photo_paths ? name)));
drop policy if exists car_photos_insert on storage.objects;
create policy car_photos_insert on storage.objects for insert to authenticated with check(bucket_id='car-photos' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists car_photos_update on storage.objects;
create policy car_photos_update on storage.objects for update to authenticated using(bucket_id='car-photos' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='car-photos' and (storage.foldername(name))[1]=auth.uid()::text);

insert into public.cars(client_id,brand,model,year,transmission,mileage,description,address,price_per_day,active)
values
 ('00000000-0000-4000-8000-000000000001','Toyota','Camry',2022,'Автоматическая',25000,'Учебный автомобиль, комфортный седан','Москва, ул. Тверская, 12',4200,true),
 ('00000000-0000-4000-8000-000000000002','BMW','X3',2023,'Автоматическая',15000,'Учебный автомобиль, кроссовер','Москва, Ленинградский проспект, 20',6900,true),
 ('00000000-0000-4000-8000-000000000003','Kia','K5',2022,'Автоматическая',30000,'Учебный автомобиль, седан','Москва, ул. Арбат, 10',3900,true),
 ('00000000-0000-4000-8000-000000000004','Tesla','Model 3',2023,'Автоматическая',18000,'Учебный электромобиль','Москва, ул. Профсоюзная, 15',7400,true),
 ('00000000-0000-4000-8000-000000000005','Volkswagen','Polo',2021,'Автоматическая',40000,'Учебный автомобиль, компактный седан','Москва, ул. Садовая, 5',2800,true)
on conflict(client_id) do nothing;
commit;
